export const userImagesRequires = [
    ["Default", require("../../assets/profiles/Default.png")],
    ["Michelle",require("../../assets/profiles/Michelle.png")],
    ["Alexandre Mondego", require('../../assets/profiles/AlexandreMondego.jpeg')],
    ["Ines Antunes", require('../../assets/profiles/InesAntunes.jpeg')],
    ["Joana Barroso", require('../../assets/profiles/JoanaBarroso.jpeg')],
    ["Sofia Alexandra", require('../../assets/profiles/SofiaAlexandra.jpeg')],
    ["Tiago Alberto", require('../../assets/profiles/TiagoAlberto.jpeg')],
    ["Tiago Mesquita", require('../../assets/profiles/TiagoMesquita.jpeg')],
    ['Rodrigo', require('../../assets/profiles/Rodrigo.jpg')],
]

export const needsImageRequires = [
    ['Default', require('../../assets/needs/Default.png')],
    ['baixo', require('../../assets/needs/baixo.jpg')],
    ['bicicleta1', require('../../assets/needs/bicicleta1.jpg')],
    ['calças', require('../../assets/needs/calças.jpeg')],
    ['calculadora', require('../../assets/needs/calculadora.jpg')],
    ['Camisa', require('../../assets/needs/Camisa.png')],
    ['canalizador', require('../../assets/needs/canalizador.png')],
    ['carro', require('../../assets/needs/carro.png')],
    ['CasacoCabedal', require('../../assets/needs/CasacoCabedal.png')],
    ['comida1', require('../../assets/needs/comida1.png')],
    ['computador', require('../../assets/needs/computador.png')],
    ['Explicações', require('../../assets/needs/Explicações.png')],
    ['guitarra', require('../../assets/needs/guitarra.png')],
    ['moto1', require('../../assets/needs/moto1.jpg')],
    ['ProBono', require('../../assets/needs/ProBono.png')],
    ['ReparosCarros', require('../../assets/needs/ReparosCarros.png')],
    ['trotinete', require('../../assets/needs/trotinete.jpeg')],
]